### ISSUE TITLE
Play whole album

### ISSUE THREAD

**Issue by foneworkshop** [CommandFusion/XBMC#16]
Hi Terence,

Just wondered if you had added anything to the xbmc demo regarding "Play next track " in album list.  I have incorporated a lot of my own GUI and am trying to avoid too much re-writing

Cheers

**Comment by CF-Terence** [comment]
Will release an update on this soon. Still needs a bit of testing of the updated code as it seems that using a different parameter for the Player.Open method will cause the playlist to play differently. 

Using the "file" parameter only enables the item in the playlist to be played one by one but "position" will enable to automatic playing of the next track in the whole playlist. 

Updated the Player.Open method now to use "position" instead of "file".

**Comment by foneworkshop** [comment]
Hi Terence,

thanks for the response. Just confused, the last line says "updated the player" does that mean you have  now done it and I just need to change a line. If so where is it in the script so |I can edit it manually

Thanks Again

**Comment by CF-Terence** [comment]
It haven't been committed yet. Basically the whole idea is that you'll need to  :
1. Add icon on the Album page to play the whole album.
2. Assign command and add script for the playing the album.
3. Modify the Playlist portion to use "position" instead of "file" for the "Player.Open" method.

Drop me an email at terence@commandfusion.com and I'll guide you through it cos it'll be a bit too long to put here in detail.

**Comment by CF-Terence** [comment]
Released on latest commit 9bd2c0c840
