### ISSUE TITLE
Problems playing music

### ISSUE THREAD

**Issue by denisrenesto** [CommandFusion/XBMC#26]
Terence,

I'm doing tests with XBMC and when I try to play some tunes, nothing happens.

If I try to play the same music through a web-browser on xbmc (http://192.168.1.3:8080) the music is played.

I know it's difficult to answer without doing any analysis or without read any log, but you know what might be happening?

This only happens with 40% of the songs in the library ...

Not had any problems with movies ...

I saw the JS file. 

```
self.playSong = function(file) {                
    if (file === undefined) {
        var file = self.currentSongFile;
    }
    self.rpc("Player.Open", { "item": {"file": file} }, self.logReplyData);
    //self.getAudioPlayerStatus();      // Set feedback status on Play/Pause button
};
```

The problem is not in variable "file"?. 

Thanks for the help.

**Comment by denisrenesto** [comment]
And if try to play through the Music ID?

I'll do some tests...

{"jsonrpc": "2.0", "method": "Player.Open", "params": { "item": { "songid": ' + song_id + ' } }, "id": 1}

**Comment by CF-Terence** [comment]
If you're able to play some songs (or I would say any songs at all), then I would say it not the issue with the module but most probably the path of the song files itself or due to certain characteristics in the song file naming i.e. dash, special symbols, etc.

Have you compared both the full path of the working and non-working song files and try to see the difference? Perhaps you can zip and send to me both a few working and non-working song files to let me have a look? 

Thanks.
